// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq8Xf5CsyN-2lx5jXHsNfdHLFZVjCfCiE',
    appId: '1:38117005133:web:003736cc2ce6d6a46cc904',
    messagingSenderId: '38117005133',
    projectId: 'finance-d38b9',
    authDomain: 'finance-d38b9.firebaseapp.com',
    storageBucket: 'finance-d38b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXDtHNhtaXSMP1JpcFty0FJbcd7_5T_ww',
    appId: '1:38117005133:android:d31c9ab5d3c1af616cc904',
    messagingSenderId: '38117005133',
    projectId: 'finance-d38b9',
    storageBucket: 'finance-d38b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdLU8a3CoKagqGWZTPKm7pLzzofsXXimM',
    appId: '1:38117005133:ios:4b5ee0f10831c7df6cc904',
    messagingSenderId: '38117005133',
    projectId: 'finance-d38b9',
    storageBucket: 'finance-d38b9.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdLU8a3CoKagqGWZTPKm7pLzzofsXXimM',
    appId: '1:38117005133:ios:4b5ee0f10831c7df6cc904',
    messagingSenderId: '38117005133',
    projectId: 'finance-d38b9',
    storageBucket: 'finance-d38b9.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq8Xf5CsyN-2lx5jXHsNfdHLFZVjCfCiE',
    appId: '1:38117005133:web:a1a54dc850cbf00b6cc904',
    messagingSenderId: '38117005133',
    projectId: 'finance-d38b9',
    authDomain: 'finance-d38b9.firebaseapp.com',
    storageBucket: 'finance-d38b9.firebasestorage.app',
  );
}
